name: Python CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r "M1_CICD Pipeline/requirements.txt"
        pip install flake8 pytest

    - name: Lint code
      run: flake8 "M1_CICD Pipeline/src/"

    - name: Run Tests
      run: pytest "M1_CICD Pipeline/tests/"

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures deployment runs after tests pass
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
  
    - name: Install dependencies
      run: |
        pip install -r "M1_CICD Pipeline/requirements.txt"
  
    - name: Save model if not already saved
      run: |
        # Ensure the models directory exists
        mkdir -p "model"
  
        # Check if the model file exists and save it
        if [ ! -f "M1_CICD Pipeline/model/housing_model.pkl" ]; then
          echo "Model file not found, training model..."
          python M1_CICD Pipeline/src/train_model.py
        else
          echo "Model file already exists, skipping training."
        fi
  
    - name: Deploy to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        model_file_path="model/housing_model.pkl"
        if [ -f "$model_file_path" ]; then
          echo "Model file found, proceeding with deployment."
          aws s3 cp "$model_file_path" s3://your-bucket-name/housing_model.pkl
        else
          echo "Model file not found. Deployment failed."
          exit 1
        fi
  
    - name: Confirm Deployment
      run: echo "Deployment to S3 completed successfully."
