name: Python CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r "M1_CICD Pipeline/requirements.txt"
        pip install flake8 pytest

    - name: Lint code
      run: flake8 "M1_CICD Pipeline/src/"

    - name: Run tests
      run: pytest "M1_CICD Pipeline/src/tests/"
