name: Python CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r "M1_CICD Pipeline/requirements.txt"
        pip install flake8 pytest

    - name: Lint code
      run: flake8 "M1_CICD Pipeline/src/"

    - name: Run Tests
      run: pytest "M1_CICD Pipeline/tests/"

  # Job for deployment
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures deployment runs after tests pass

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r "M1_CICD Pipeline/requirements.txt"

    - name: Deploy to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        # Assuming you have a model file like 'housing_model.pkl' or an artifact to deploy
        aws s3 cp "M1_CICD Pipeline/model/housing_model.pkl" s3://your-bucket-name/housing_model.pkl

    - name: Confirm Deployment
      run: echo "Deployment to S3 completed successfully."
